config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :activities, only: [:index]
    resources :teams, only: [:index]
  end

  devise_for :users
  resources :location, only: [:new]
  resources :activities, only: [] do
    resources :uploads, only: [:destroy]
  end

  resources :match, only: [:show] do
    resources :teams, except: [:index, :update]
    resources :main, only: [:index]
    resources :team_invitations, only: [:new, :create]
    resource :user, only: [:update]

    resources :projects, except: [:index, :destroy] do
      resources :feedbacks, only: [:index, :create, :update]
    end
    resources :activities, except: [:index] do
      resources :feedbacks, only: [:index, :create, :update]
    end
    resources :polls, only: [:show] do
      resources :content, only: [] do
        resources :votes, only: [:create, :destroy]
      end
    end

    namespace :judge do
      resources :polls, only: [:show]
      resources :main, only: [:index]
      resources :activities, only: [:show, :update] do
        resources :content_approvations, only: [:create, :destroy]
        resources :feedbacks, only: [:index, :create, :update]
        resources :locations, only: [:update]
      end
      resources :projects, only: [] do
        resources :content_approvations, only: [:create, :destroy]
      end
    end

    as :user do
      get '/users' => 'devise_invitable/registrations#new'
      get '/teams' => 'teams#new'
      get '/team_invitation' => 'team_invitations#new'
      get '/activities' => 'activities#new'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'landing_page#index'

  namespace :admin do
    resources :user_manager, only: [:index, :update, :destroy]
    resources :matches
  end
end

app/models/poll.rb
# == Schema Information
#
# Table name: polls
#
#  id         :bigint(8)        not null, primary key
#  start_date :date             not null
#  end_date   :date             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  match_id   :bigint(8)
#

class Poll < ApplicationRecord
  belongs_to :match
  has_many :votes, dependent: :destroy
  has_many :projects, -> { where(status: 2) }, through: :match
  has_many :activities, through: :match
  has_many :users, through: :activities
  has_many :teams, through: :users

  scope :pending_polls, (lambda { |date|
    where('(polls.start_date > ?) OR polls.end_date > ? ', date, date)
  })

  scope :last_ended_poll, (lambda { |date|
    where('polls.end_date < ?', date)
    .order('end_date desc')
  })

  scope :users_can_vote, (lambda { |date|
    where('polls.end_date >= ? and polls.start_date <= ?', date, date)
  })

  validates :start_date, :end_date, presence: true
  validate :valid_date_range

  def activities_by_type
    activities.includes(:votes)
              .where(status: 2)
              .order(:name)
              .group_by(&:activity_type)
  end

  def can_vote?
    actual_date = Time.now.in_time_zone('Mexico City').to_date
    end_date >= actual_date && start_date <= actual_date
  end

  def judge_votes
    votes.where(user: { role: 1 })
  end

  def user_has_voted?(user)
    votes.where(user: user).present?
  end

  def user_votes(user)
    votes.where(user: user)
  end

  def voted_for_activity_type?(activity, user)
    votes.where(user: user)
         .joins('inner join activities on activities.id = votes.content_id')
         .where(activities: { activity_type: Activity.activity_types.fetch(activity.activity_type) })
         .any?
  end
end

def valid_date_range
  errors.add(:start_date, I18n.t('polls.error_date_start')) if start_date < Date.today
  errors.add(:start_date, I18n.t('polls.error_dates')) if end_date <= start_date
end

app/controllers/polls_controller.rb
class PollsController < MatchesController
  before_action :user_can_access?

  def show
    @poll.match.content_match? ? initialize_activities : initialize_projects
  end

  private

  def initialize_activities
    @activities_votes = if current_user.judge?
                          @poll.judge_votes
                        else
                          @poll.user_votes(current_user)
                        end
    @activity_types = @poll.activities.group(:activity_type).select(:activity_type)
    @best_activities = []
    3.times { |i| @best_activities << Activity.best_activities(@poll.id, i) }
  end

  def initialize_projects
    @contents = @poll.projects
  end

  def user_can_access?
    @poll = Poll.find(params[:id])
    return if @poll.can_vote? && (@poll.activities.any? || @poll.projects.any?)

    validate_poll_content
    flash[:alert] = t('poll.error_accesing') unless @poll.can_vote?
    redirect_to match_main_index_path(@match)
  end

  def validate_poll_content
    flash[:alert] = t('poll.empty_activities') if @poll.match.content_match? && @poll.activities.empty?
    flash[:alert] = t('poll.empty_projects') if @poll.match.project_match? && @poll.projects.empty?
  end
end

app/helpers/poll_helper.rb
module PollHelper
  def user_has_voted_for(content)
    @vote ||= @poll.votes.where(user: current_user)
    @vote.find_by(content_id: content.id).present?
  end

  def judges_has_voted_for(content)
    @vote ||= @poll.votes
    @vote.find_by(content_id: content.id).present?
  end
end

app/views/admin/polls/_form.html.haml
= simple_form_for [:admin, @match, @poll] do |f|
  = f.error :base
  .form-group
    %p
      = t('labels.start_date')
      = f.date_select :start_date, start_year: Date.today.year, end_year: Date.today.year+1, class: "form-control"
  .form-group
    %p
      = t('labels.end_date')
      = f.date_select :end_date, start_year: Date.today.year,  end_year:  Date.today.year+1, class: "form-control"
  %h4
    = t('labels.activities_range')
  .form-group
    %p
      = t('labels.start_date')
      = f.date_select :activities_from, class: "form-control", start_year: Date.today.year, end_year: Date.today.year+1
  .form-group
    %p
      = t('labels.end_date')
      = f.date_select :activities_to, class: "form-control", start_year: Date.today.year, end_year: Date.today.year+1

  = f.button :submit, option, class:'button'

app/views/admin/polls/edit.html.haml
.center-vertical.admin-poll
  .main-content.medium.container
    %h2
      = t('poll.edit_poll')

    = render "form", option: t('buttons.update')

app/views/admin/polls/index.html.haml
.main-content.container.medium.mt-5
  .contain.center-vertical.admin-poll
    - unless @polls.empty?
      %h3.mt-5.text.center.mb-3.poll
        = t('poll.title')
      %br
      %table.activities-table
        %thead.mb-3
          %tr
            %th
              = t('labels.polls')
            %th.text-center
              = t('poll.votes')
            %th.text-right
              = t('buttons.actions')
        %tbody
          - @polls&.each do |poll|
            %tr
              %td
                = t('votes.vote_range', start_date: poll.start_date, end_date: poll.end_date)
              %td.text-center
                = poll.votes.count
              %td.text-right.poll-actions
                = link_to image_tag('ic-edit'), edit_admin_match_poll_path(@match, poll)
                = link_to image_tag('ic-delete'), admin_match_poll_path(@match, poll), method: :delete, data: {confirm:t('actions.confirm') }
    %br
    = link_to t('poll.create_new'), new_admin_poll_path, class: 'button' if allowed_to_create_poll

app/views/admin/polls/new.html.haml
.center-vertical.admin-poll
  .main-content.medium.container
    %h2
      = t('poll.create_new')

    = render "form", option: t('buttons.new')