config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :activities, only: [:index]
    resources :teams, only: [:index]
  end

  devise_for :users
  resources :location, only: [:new]
  resources :activities, only: [] do
    resources :uploads, only: [:destroy]
  end

  resources :match, only: [:show] do
    resources :teams, except: [:index, :update]
    resources :main, only: [:index]
    resources :team_invitations, only: [:new, :create]
    resource :user, only: [:update]

    resources :projects, except: [:index, :destroy] do
      resources :feedbacks, only: [:index, :create, :update]
    end
    resources :activities, except: [:index] do
      resources :feedbacks, only: [:index, :create, :update]
    end
    resources :polls, only: [:show] do
      resources :content, only: [] do
        resources :votes, only: [:create, :destroy]
      end
    end

    namespace :judge do
      resources :polls, only: [:show]
      resources :main, only: [:index]
      resources :activities, only: [:show, :update] do
        resources :content_approvations, only: [:create, :destroy]
        resources :feedbacks, only: [:index, :create, :update]
        resources :locations, only: [:update]
      end
      resources :projects, only: [] do
        resources :content_approvations, only: [:create, :destroy]
      end
    end

    as :user do
      get '/users' => 'devise_invitable/registrations#new'
      get '/teams' => 'teams#new'
      get '/team_invitation' => 'team_invitations#new'
      get '/activities' => 'activities#new'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'landing_page#index'

  namespace :admin do
    resources :user_manager, only: [:index, :update, :destroy]
    resources :matches
  end
end

app/models/match.rb
# == Schema Information
#
# Table name: matches
#
#  id         :bigint(8)        not null, primary key
#  match_type :integer
#  version    :integer
#  start_date :datetime
#  end_date   :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Match < ApplicationRecord
  before_create :assign_version
  after_create :create_poll

  enum match_type: %i[Content Project]

  has_many :activities, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_many :teams, dependent: :destroy
  has_one :poll, dependent: :delete

  validates :match_type, :start_date, :end_date, presence: true
  validate :dates_match?, :no_overlaps?

  scope :active_match, -> { where('? BETWEEN start_date AND end_date', Date.today) }

  def active?
    actual_date = Date.today.in_time_zone('Mexico City')
    (start_date..end_date).cover?(actual_date)
  end

  def assign_version
    latest_version = Match.where(match_type: match_type).max_by(&:version)&.version || 0
    self.version = latest_version + 1
  end

  def dates_match?
    errors.add(:end_date, I18n.t('errors.end_date_invalid')) if start_date > end_date
  end

  def content_match?
    Content?
  end

  def create_poll
    Poll.create(start_date: end_date + 1,
                end_date: end_date + 7.days,
                match: self)
  end

  def no_overlaps?
    dates = Match.all.select(:id, :start_date, :end_date)
    dates.each do |date|
      next unless (start_date..end_date).overlaps?(date.start_date..date.end_date) && date.id != id

      errors.add(:start_date, format(I18n.t('errors.overlapped_dates'), match_id: date.id,
                                                                        start_date: date.start_date,
                                                                        end_date: date.end_date))
    end
  end

  def last_three_activities
    activities.order(created_at: :desc).limit(3)
  end

  def leader_team
    teams.max_by(&:score)
  end

  def top_teams(teams_number)
    teams.sort_by(&:score).reverse&.first(teams_number)
  end

  def pending_user_approves(user)
    if content_match?
      activities.where.not(name: activities.joins(:approvations)
                                           .where(content_approvations: { user_id: user.id }).pluck(:name))
    else
      projects.where.not(name: projects.joins(:approvations)
                                       .where(content_approvations: { user_id: user.id }).pluck(:name))
    end
  end

  def project_match?
    Project?
  end

  def teams_by_score
    teams.sort_by(&:score).reverse!
  end

  def total_score
    activities.where(status: 2).sum(:score)
  end

  def winner_team
    teams.max_by(&:score)
  end
end

app/controllers/admin/matches_controller.rb
module Admin
  class MatchesController < AdminController
    before_action :set_match, only: [:show, :edit, :update, :destroy]
    def index
      @matches = Match.all
    end

    def show; end

    def new
      @match = Match.new
    end

    def create
      @match = Match.new(match_params)
      if @match.save
        flash[:notice] = t('match.create')
        redirect_to admin_matches_path
      else
        flash[:alert] = @match.errors.full_messages.first
        render 'new'
      end
    end

    def edit; end

    def update
      if @match.update(match_params)
        flash[:notice] = t('match.update')
        redirect_to admin_matches_path
      else
        flash[:error] = @match.errors.full_messages.first
        render 'edit'
      end
    end

    def destroy
      if @match.destroy
        flash[:notice] = t('match.delete')
      else
        flash[:error] = t('match.error_deleting')
      end
      redirect_to admin_matches_path
    end

    private

    def match_params
      params.require(:match).permit(:match_type, :start_date, :end_date)
    end

    def set_match
      @match = Match.find(params[:id])
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :assign_match

  def assign_match
    @match = Match.find(params[:match_id])
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/admin/matches/_form.html.haml
= simple_form_for [:admin, @match] do |f|
  = f.error :base
  .form-group
    %p
      = t('labels.start_date')
      = f.date_select :start_date, start_year: Date.today.year, end_year: Date.today.year+1, class: "form-control"
  .form-group
    %p
      = t('labels.end_date')
      = f.date_select :end_date, start_year: Date.today.year, end_year: Date.today.year+1, class: "form-control"
  .form-match-group
    = f.input :match_type, disabled:  @match.persisted?, label: t('labels.match_type'), label_html: { class: 'match_center' }, input_html: { class: 'input-text' }, include_blank: false, collection: Match.match_types.keys
  = f.button :submit, option, class: 'button'

app/views/admin/matches/edit.html.haml
.center-vertical.admin-matches
  .main-content.medium.container
    %h2
      = t('match.edit')

    = render'form', option: t('buttons.update')

app/views/admin/matches/index.html.haml
.center-vertical.match-list
  %table.match-table
    %tr.center-info
      %th
        = t('labels.match_type')
      %th
        = t('labels.version')
      %th
        = t('labels.start_date')
      %th
        = t('labels.end_date')
      %th
        = t('labels.leader')
      %th{colspan: 3}
        = t('buttons.actions')

    - @matches.each do |m|
      %tr.center-info
        %td
          = m.match_type
        %td
          = m.version
        %td
          = m.start_date.to_date
        %td
          = m.end_date.to_date
        %td
          = m.leader_team&.name || t('team.messages.no_leader')
        %td.match-actions
          = link_to image_tag('ic-prize'), admin_match_path(m)
        %td.match-actions
          = link_to image_tag('ic-edit'), edit_admin_match_path(m)
        %td.match-actions
          = link_to image_tag('ic-delete'), admin_match_path(m), method: :delete, data: {confirm: t('actions.confirm')}


  %p.center-info
    = link_to t('buttons.new'), new_admin_match_path

app/views/admin/matches/new.html.haml
.center-vertical.admin-matches
  .main-content.medium.container
    %h2
      = t('match.create_new')

    = render'form', option: t('buttons.new')

app/views/admin/matches/show.html.haml
%p
  %h3
    = t('labels.match_type')
  = @match.match_type
%p
  %h3
    = t('labels.version')
  = @match.version
%p 
  %h3
    = t('labels.start_date')
  = @match.start_date
%p
  %h3
    = t('labels.end_date')
  = @match.end_date