config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :activities, only: [:index]
    resources :teams, only: [:index]
  end

  devise_for :users
  resources :location, only: [:new]
  resources :activities, only: [] do
    resources :uploads, only: [:destroy]
  end

  resources :match, only: [:show] do
    resources :teams, except: [:index, :update]
    resources :main, only: [:index]
    resources :team_invitations, only: [:new, :create]
    resource :user, only: [:update]

    resources :projects, except: [:index, :destroy] do
      resources :feedbacks, only: [:index, :create, :update]
    end
    resources :activities, except: [:index] do
      resources :feedbacks, only: [:index, :create, :update]
    end
    resources :polls, only: [:show] do
      resources :content, only: [] do
        resources :votes, only: [:create, :destroy]
      end
    end

    namespace :judge do
      resources :polls, only: [:show]
      resources :main, only: [:index]
      resources :activities, only: [:show, :update] do
        resources :content_approvations, only: [:create, :destroy]
        resources :feedbacks, only: [:index, :create, :update]
        resources :locations, only: [:update]
      end
      resources :projects, only: [] do
        resources :content_approvations, only: [:create, :destroy]
      end
    end

    as :user do
      get '/users' => 'devise_invitable/registrations#new'
      get '/teams' => 'teams#new'
      get '/team_invitation' => 'team_invitations#new'
      get '/activities' => 'activities#new'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'landing_page#index'

  namespace :admin do
    resources :user_manager, only: [:index, :update, :destroy]
    resources :matches
  end
end

app/views/welcome/_footer.html.haml
.wraper-footer
  .footer
    .container.container-info
      .container-about
        = image_tag 'github-logo', alt: 'github', height: '25px', width: '25px', class: 'github-icon'
        = link_to(t('information.footer.about'), 'https://git.michelada.io/michelada/mcm')
      .container-extra-info
        %p= t('information.footer.copyrights')

app/views/welcome/_header.html.haml
%header
  - if user_signed_in?
    .container.header
      = link_to match_main_index_path do
        - if @match.content_match?
          = image_tag 'mcm-logo', alt: 'mcm-logo', height: 60, class: 'company-logo'
        - elsif @match.project_match?
          = image_tag 'mpm-logo', alt: 'mpm-logo', height: 60, class: 'company-logo'
        - else
          = image_tag 'michelada-logo', alt: 'michelada-logo', height: 60, class: 'company-logo'
      .nav
        - if @match.content_match?
          = link_to new_match_activity_path(@match) do
            = render partial: 'icons/ic_activities', locals: {is_active: controller_path == 'activities' }
        - elsif @match.project_match? && can_upload_project?
          = link_to new_match_project_path(@match) do
            = render partial: 'icons/ic_activities', locals: {is_active: controller_path == 'projects' }
        = link_to  match_main_index_path(@match) do
          = render partial: 'icons/ic_top', locals: {is_active: controller_path == 'main' }
        = link_to  new_match_team_path(@match) do
          = render partial: 'icons/ic_team', locals: {is_active: controller_path == 'teams' }
        - if current_user.judge?
          = link_to match_judge_main_index_path(@match) do
            = render partial: 'icons/ic_judge', locals: {is_active: ((controller_path.include?('judge')) && controller_path != 'judge/polls') }
        - if poll_for_vote
          = link_to  match_poll_path(@match, @match.poll) do
            = render partial: 'icons/ic_poll', locals: {is_active: controller_path == 'polls' }