config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :activities, only: [:index]
    resources :teams, only: [:index]
  end

  devise_for :users
  resources :location, only: [:new]
  resources :activities, only: [] do
    resources :uploads, only: [:destroy]
  end

  resources :match, only: [:show] do
    resources :teams, except: [:index, :update]
    resources :main, only: [:index]
    resources :team_invitations, only: [:new, :create]
    resource :user, only: [:update]

    resources :projects, except: [:index, :destroy] do
      resources :feedbacks, only: [:index, :create, :update]
    end
    resources :activities, except: [:index] do
      resources :feedbacks, only: [:index, :create, :update]
    end
    resources :polls, only: [:show] do
      resources :content, only: [] do
        resources :votes, only: [:create, :destroy]
      end
    end

    namespace :judge do
      resources :polls, only: [:show]
      resources :main, only: [:index]
      resources :activities, only: [:show, :update] do
        resources :content_approvations, only: [:create, :destroy]
        resources :feedbacks, only: [:index, :create, :update]
        resources :locations, only: [:update]
      end
      resources :projects, only: [] do
        resources :content_approvations, only: [:create, :destroy]
      end
    end

    as :user do
      get '/users' => 'devise_invitable/registrations#new'
      get '/teams' => 'teams#new'
      get '/team_invitation' => 'team_invitations#new'
      get '/activities' => 'activities#new'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'landing_page#index'

  namespace :admin do
    resources :user_manager, only: [:index, :update, :destroy]
    resources :matches
  end
end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id               :bigint(8)        not null, primary key
#  name             :string           not null
#  english          :boolean          not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  user_id          :bigint(8)        not null
#  activity_type    :integer          not null
#  status           :integer          default("Por validar"), not null
#  notes            :text
#  score            :integer          default(0)
#  description      :text
#  pitch_audience   :text
#  abstract_outline :text
#  files            :string
#  english_approve  :boolean
#  slug             :string
#  match_id         :bigint(8)
#

class Activity < ApplicationRecord
  extend FriendlyId
  belongs_to :match
  belongs_to :user
  has_many :feedbacks, as: :commentable, dependent: :destroy
  has_many :locations, dependent: :destroy
  has_many :approvations, as: :content, dependent: :destroy, class_name: 'ActivityStatus'
  has_many :votes,  as: :content, dependent: :destroy
  has_many_attached :files, dependent: :destroy
  accepts_nested_attributes_for :locations, allow_destroy: true, reject_if: :created_whithout_name
  friendly_id :name, use: :slugged
  enum activity_type: %i[Curso Plática Post]
  enum status: %i[Por\ validar En\ revisión Aprobado]
  before_save :assign_score
  before_update :mark_locations_for_removal, :match_valid?, :update_score

  scope :from_a_poll, (lambda { |start_date, end_date|
    where('created_at >= ? AND created_at <= ? AND status = ?', start_date, end_date, 2)
  })
  scope :checked_activities, ->(actual_user) { joins(:statuses).where('activity_statuses.user_id = ?', actual_user).select('activities.id') }
  scope :unapproved, ->(actual_user) { where('activities.id IN (?)', checked_activities(actual_user)).order('name ASC') }
  scope :pending_activities, ->(actual_user) { where('activities.id NOT IN (?)', checked_activities(actual_user)).order('name ASC') }
  scope :order_by_name, -> { order('name ASC') }
  scope :best_activities, (lambda { |poll_id, type|
    joins(:votes)
    .where('votes.poll_id = ?', poll_id)
    .where('activities.activity_type = ?', type)
    .group('activities.name, activities.activity_type')
    .select('activities.name, activities.activity_type ,sum(votes.value) as points')
    .order('points desc').limit(1)
  })
  scope :sort_by_creation, -> { order('created_at DESC') }
  validates :pitch_audience, :abstract_outline, :description, presence: true, unless: :post?
  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }
  validate :belongs_to_content_match?

  def belongs_to_content_match?
    errors.add(:match_id, I18n.t('errors.no_content_match')) if match&.match_type != 'Content'
  end

  def css_class
    status_class = { "Por validar": 'on-hold', "En revisión": 'review', "Aprobado": 'approved' }
    status_class[status.to_sym]
  end

  def approved?
    Aprobado?
  end

  def assign_score
    self.score = score_by_type
  end

  def team
    user.current_team
  end

  def to_param
    slug
  end

  def should_generate_new_friendly_id?
    name_changed?
  end

  def workshop?
    Curso?
  end

  def talk?
    Plática?
  end

  def post?
    Post?
  end

  def can_edit?(user_id)
    user.id == user_id
  end

  def created_whithout_name(location)
    location[:name].blank? && new_record?
  end

  def mark_locations_for_removal
    locations.each do |location|
      location.mark_for_destruction if location.name.blank?
    end
  end

  def match_valid?
    raise 'Activity can only exist in project matches' if match.match_type != 'Content'
  end

  def score_by_type
    case activity_type
    when 'Curso'
      40
    when 'Plática'
      25
    when 'Post'
      10
    end
  end

  def status_by_user(user)
    approvations.find_by(user: user)
  end

  def update_score
    accumulated_score = score_by_type
    accumulated_score += 5 if english_approve
    events_extra_points = Post? ? 5 : 15
    accumulated_score += events_extra_points * locations.where(approve: true).count
    self.score = accumulated_score
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < MatchesController
  before_action :user_can_edit_activity?, only: [:edit, :update, :destroy]
  before_action :user_can_upload_activity?, only: [:new, :create]

  def new
    @activity = Activity.new
    @activity.locations.build
    @feedback = Feedback.new
  end

  def create
    @activity = Activity.new(activity_params)
    if @activity.save
      flash[:notice] = t('activities.messages.uploaded')
      redirect_to match_team_path(params[:match_id], current_user.current_team)
    else
      @activity.locations.build if @activity.locations.blank?
      flash.now[:alert] = t('activities.messages.error_creating')
      render 'new'
    end
  end

  def show
    @activity = Activity.friendly.find(params[:id])
    @feedback = Feedback.new
  end

  def destroy
    activity = Activity.friendly.find(params[:id])
    if !activity.approved? && activity.destroy
      flash[:notice] = t('activities.messages.deleted')
    else
      flash[:alert] = t('activities.messages.error_deleting')
    end
    redirect_to match_team_path(params[:match_id], current_user.current_team)
  end

  def edit
    @activity = Activity.friendly.find(params[:id])
  end

  def update
    @activity = Activity.friendly.find(params[:id])
    if @activity.update(activity_params)
      flash[:notice] = t('activities.messages.updated')
      redirect_to match_team_path(params[:match_id], current_user.current_team)
    else
      flash.now[:alert] = t('alerts.activities.not_black')
      render 'edit'
    end
  end

  private

  def activity_params
    params.require(:activity)
          .permit(:name, :english,
                  :activity_type,
                  :description, :pitch_audience,
                  :abstract_outline, :notes,
                  files: [],
                  locations_attributes: [:name, :id, :_destroy])
          .merge(match_id: params[:match_id], user: current_user)
  end

  def user_can_edit_activity?
    activity = Activity.friendly.find(params[:id])
    return unless activity.approved?

    flash[:alert] = t('activities.messages.error_accessing')
    redirect_to root_path
  end

  def user_can_upload_activity?
    match = Match.find(params[:match_id])
    if match.content_match?
      if current_user.current_team
        return if match.active?

        flash[:alert] = t('activities.closed')
        redirect_to match_main_index_path(@match)
      else
        flash[:alert] = t('projects.no_team')
        redirect_to new_match_team_path(@match)
      end
    else
      flash[:alert] = t('match.error_type')
      redirect_to root_path
    end
  end
end

app/controllers/api/activities_controller.rb
module Api
  class ActivitiesController < ::ActionController::Base
    def index
      return project_match_message unless Match.last.content_match?

      Match.last.active? ? last_activity : best_three_activities
    end

    def last_activity
      last_activity = Activity.last
      response = ::Api::ApiService.new.last_activity_format(last_activity)
      render json: response
    end

    def best_three_activities
      best_activities = []
      3.times { |i| best_activities << Activity.best_activities(Poll.last, i) }
      response = ::Api::ApiService.new.top_activities_format(best_activities)
      render json: response
    end

    def project_match_message
      response = ::Api::ApiService.new.project_match_message
      render json: response
    end
  end
end

app/controllers/judge/activities_controller.rb
module Judge
  class ActivitiesController < JudgeController
    def show
      @activity = Activity.friendly.find(params[:id])
      @feedback = Feedback.new
    end

    def update
      @activity = Activity.friendly.find(params[:id])
      @activity.update_attributes(english_approve: !@activity.english_approve)
      message = @activity.english_approve ? t('labels.english_approved') : t('labels.english_unapproved')
      flash[:notice] = message
      redirect_to match_activity_path(@match, @activity)
    end
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
  def judges_appproves(activity)
    activity.approvations.collect { |status| status.user.email.remove('@michelada.io') }.join(', ')
  end

  def sorted_comments(commentable)
    commentable.feedbacks.sort_by(&:created_at)
  end

  def user_name(user)
    user.name? ? user.name : user.email.remove('@michelada.io').capitalize
  end
end

app/helpers/judge/activities_helper.rb
module Judge
  module ActivitiesHelper
  end
end

app/views/activities/_comment_form.html.haml
= simple_form_for [ @match, @activity, @feedback] do |f|
  = f.text_area :comment, label: t('comments.create'), placeholder: t('placeholders.comment'), input_html: { class: 'input-text mt-4'}, required: false
  .comment-actions
    %ul
      %li#boldButton
        = link_to t('buttons.markdown.bold'), ''
      %li#italicButton
        = link_to t('buttons.markdown.italic'), ''
      %li#codeButton
        = link_to t('buttons.markdown.code'), ''
      %li#linkButton
        = link_to t('buttons.markdown.link'), ''
      %li#quoteButton
        = link_to t('buttons.markdown.quote'), ''
      %li#listButton
        = link_to t('buttons.markdown.list'), ''
  = f.file_field :file, class:'inputfile', accept: '.jpg,.png,.jpeg'
  = f.button :submit, t('comments.create'), class: 'button'

app/views/activities/_comments.html.haml
- sorted_comments(@activity).each_with_index do |feedback, i|
  %div{:id => "com_#{i}", class: 'comment'}
    %h6.gray.d-flex.justify-content-between{class: feedback.user.judge? ? 'judge' : 'regular'}
      = user_name(feedback.user)
      - if feedback.user == current_user
        .original_comment
          %input{type: 'hidden', value: feedback.comment, id: "originalText_#{i}"}
        .edit_comment
          = link_to t('buttons.edit'), '#', :id => "#{i}"
        .form_data
          %input{ type: 'hidden', id: "commentId#{i}", value: "#{@activity.id}"}
          %input{ type: 'hidden', id: "feedbackId#{i}", value: "#{feedback.id}"}
    .comment-content
      %p{ class: 'gray', id: "comment_#{i}", class: 'mt-3'}
        = markdown(feedback.comment, feedback.file)
      %textarea{ value: "#{feedback.comment}", hidden: true, id: "editor_#{i}", class: 'input-text mb-0 mt-2'}

app/views/activities/_english_locations.html.haml
-if @activity.english
  %h6.text.red= t('labels.english')
  %p
    - if @activity.english_approve
      = image_tag('ic-checked', class: "check-activity approve-#{@activity.english_approve}")
    - else
      = image_tag('ic-not-approved', class: "check-activity approve-#{@activity.english_approve}")
    %label= t('labels.english')
%h6.text.red= t('labels.events')
- unless @activity.locations.empty?
  %ul
    - @activity.locations&.each do |events|
      %li
        -if events.approve
          = image_tag('ic-checked', class: "approve-#{events.approve} check-activity")
        -else
          = image_tag('ic-not-approved', class: "approve-#{events.approve} check-activity")
        %label= "#{events.name}"
- else
  %p= t('labels.not_location')

app/views/activities/_form.html.haml
.container.center-vertical.activities
  .main-content.medium.mt-5
    = simple_form_for([@match, @activity]) do |f|

      %label
        = t('labels.type')
      = f.select :activity_type, Activity.activity_types.keys, include_blank: false
      .mt-2
      = f.input :name, label: t("labels.name"), placeholder: t("placeholders.activity.title"), input_html: { class: 'input-text' }
      .optional-fields
        #description
          = f.input :description, label: t("labels.description"), placeholder: t("placeholders.activity.description"), input_html: { class: 'input-text optional-fields' }, required: true
        #pitch-audience
          = f.input :pitch_audience, label: t("labels.audience"), placeholder: t("placeholders.activity.audience"), input_html: { class: 'input-text optional-fields' }
        #abstract-outline
          = f.input :abstract_outline, label: t("labels.outline"), placeholder: t("placeholders.activity.guide"), input_html: { class: 'input-text optional-fields' }

      .row
        .col-sm-12.col-xs-12.mb-3
          %label=t("labels.location")
          #other_location
            %input{type: 'text', placeholder: t("placeholders.activity.event"), class: 'input-text add-location mt-2', id: 'add_location_input'}

          #location_inputs
            = f.simple_fields_for :locations do |l|
              = l.input :name, as: :hidden, class: 'locations_attribute'

      .locations_list.tags_box
        %ul
          - @activity.locations.each_with_index do |location, index|
            - unless location.name.nil?
              %li{id: index}<
                =location.name
                %a>='x'

      = f.input :notes, label: t("labels.link"), placeholder: t("placeholders.link"), input_html: { class: 'input-text' }
      = f.input :english, label: t("labels.english"), input_html: {class: 'mt-0'} , label_html: { class: 'mt-0'}

      - if @activity.files.attached? && @activity.valid?
        = t('labels.archives')
        .mt-3
          - @activity.files.each do |file|
            %p.mt-3.mb-0
              = "#{t("labels.selected_file")}: #{file.filename}"
            = link_to t('buttons.delete'), activity_upload_path(@activity.id, file.id), method: :delete, data: { confirm: t('actions.confirm')}
      = f.file_field :files, multiple: true,  class:'inputfile', :accept => '.pdf,.jpg,.png,.key,.jpeg,.zip'
      %em= t('labels.information')

      %input{type: "submit", id:"submit_button", value: t("buttons.submit"), class: 'button'}

app/views/activities/_judges_english_locations.html.haml
-if @activity.english
  %h6.text.red= t('labels.english')
  %p
    - if @activity.english_approve
      = link_to image_tag('ic-checked', class: "check-activity approve-#{@activity.english_approve}"), match_judge_activity_path(@match, @activity), method: :patch
    - else
      = link_to image_tag('ic-not-approved', class: "check-activity approve-#{@activity.english_approve}"), match_judge_activity_path(@match, @activity), method: :patch
%h6.text.red= t('labels.events')
- unless @activity.locations.empty?
  %ul
    - @activity.locations&.each do |events|
      %li
        -if events.approve
          = link_to image_tag('ic-checked', class: "check-activity approve-#{events.approve}"), match_judge_activity_location_path(@match, @activity, events), method: :patch
        -else
          = link_to image_tag('ic-not-approved', class: "check-activity approve-#{events.approve}"), match_judge_activity_location_path(@match, @activity, events), method: :patch
        %label= "#{events.name}"
- else
  %p= t('labels.not_location')

app/views/activities/edit.html.haml
= render 'form', activity: @activity, option: t('buttons.edit')

app/views/activities/new.html.haml
= render "form", activity: @activity, option: t("buttons.upload")

app/views/activities/show.html.haml
.main-content.container.medium.mt-5
  .contain.center-vertical
    .judge
      - if current_user.judge?
        %h3
          = t('user.judge.activities.on_old.remember')
          %span.text.red
            = t('user.judge.activities.on_old.objetive')
      - if @activity.status_by_user(current_user).nil?
        = link_to image_tag('ic-not-approved', class: 'check-activity approve-false', id: 'approve'),  match_judge_activity_content_approvations_path(@match, @activity), method: :post
        %label= "#{t('activities.status_approve')}"
      - else
        = link_to image_tag('ic-checked', class: 'check-activity approve-true', id: 'disapprove'), match_judge_activity_content_approvation_path(@match, @activity, @activity.status_by_user(current_user)), method: :delete, data: {confirm: t('actions.confirm')}
        %label= "#{t('activities.status_approved')}"

      %h3= @activity.name
      %h6.mt-4
        = @activity.activity_type
        %em.points=t('labels.points', { score: @activity.score })
      - if @activity.approvations.exists?
        %p
          = t('activities.approved_by', users: judges_appproves(@activity))
      -unless @activity.activity_type == 'Post'
        %h6.text.red.mt-4=t('user.judge.activities.description') if @activity.description
        %p= markdown(@activity.description)
        -if @activity.activity_type == 'Curso'
          %h6.text.red= t('user.judge.activities.intended_audence') if @activity.pitch_audience
          %p= markdown(@activity.pitch_audience)
          %h6.text.red= t('user.judge.activities.outline') if @activity.abstract_outline
          %p= markdown(@activity.abstract_outline)
        -else
          %h6.text.red= t('user.judge.activities.pitch') if @activity.pitch_audience
          %p= markdown(@activity.pitch_audience)
          %h6.text.red= t('user.judge.activities.abstract') if @activity.abstract_outline
          %p= markdown(@activity.abstract_outline)

      - unless @activity.notes&.empty?
        %h6.text.red= t("labels.link")
        %p= sanitize_links(@activity.notes)
      - if current_user.judge?
        = render 'judges_english_locations'
      - else
        = render 'english_locations'
    .activities
      - if @activity.files.attached?
        %h6.text.red= t('labels.archives')
        - @activity.files.each do |file|
          %label= file.filename
          = link_to t('labels.download'), file, disposition: "attachment", class:'button', target: :_blank
      %hr.mt-5

      %h5.mt-5.mb-5
        = t("comments.all")
      = render 'comments'

      .mt-4
        - if user_can_comment?(@activity)
          = render 'comment_form'